update corner radius
mkko/DrawerView pull request #38
Opened 2020-09-24 20:12 UTC by decanus

This should set it so the corner radius is only on top. There is a weird issue on older iphones where you see the edge of the radius at the bottom.

2020-10-24 05:01 UTC, wyszo commented
Hi! 

Could you submit a screenshot/video of the problem you're demonstrating (and ideally a sample app too). 

I have not noticed the issue you mention. 

However, I've noticed that your solution unfortunately breaks the sample app, a drawer presented modally becomes fully transparent (!): 

Because of that I strongly recommend against merging this PR in it's current version. 

If you really would like to solve this problem, here's a much better solution (that doesn't break existing code samples): 

```
private func roundTopRightLeftCorners(_ layer: CALayer) {
    if #available(iOS 11.0, *) {
        layer.maskedCorners = [
            .layerMaxXMinYCorner, // top right
            .layerMinXMinYCorner  // top left
        ]
        layer.masksToBounds = true
    }
    layer.cornerRadius = self.cornerRadius
}

private func updateLayerVisuals(_ layer: CALayer) {
    layer.shadowRadius = shadowRadius
    layer.shadowOpacity = shadowOpacity
    roundTopRightLeftCorners(layer)
}
```

This way of masking is already used in the codebase (by the `backgroundView`), so it's already proven to be fairly reliable.

2020-10-24 05:04 UTC, wyszo requested changes
Please see my comments in the conversation section. Unfortunately this solution breaks existing sample code. I suggested an alternative implementation that doesn't. Cheers!

2020-10-28 13:19 UTC, mkko commented
Thank you for the feedback on this PR. The reason it has been delayed is only because I haven't had the time to have this running and see how it works. If I remember correctly, I had issues with the corners and I had to settle for simple but ugly solution.

The issue is valid, but if it breaks the layout as wyszo mentioned, it needs to be fixed first.

2020-10-28 13:23 UTC, decanus commented
Hey @mkko the issue I actually had was mainly due to how I was setting background color. We can close this PR now.

2020-10-28 13:33 UTC, mkko commented
Oh. Was there something in the DrawerView API that was misleading? I'm thinking if we could improve that.

2021-02-25 09:57 UTC, wongzigii commented
![image](https://user-images.githubusercontent.com/7384288/109136161-c93bc480-7792-11eb-8976-e87b8180ab62.png)

I am setting the top corners likes @wyszo , but there is extra space in iPhone Pro Max Simulator. (only in iPhone Pro Max)

2021-02-26 08:38 UTC, mkko commented
Hi @wongzigii. I tried the snippet and no issues here, with Pro Max. Could you provide some simplified example where your issue occurs? It looks like a timing issue where everything is laid out before the drawer calculates its size. I might be wrong but I'd need to see your setup before I can say anything.

2021-02-26 08:38 UTC, mkko commented
Sorry, mistakenly opened this issue.

2021-02-26 08:38 UTC, closed without merging